---
- hosts: all
  become: yes
  vars_files:
    - /etc/ansible/playbooks/vars/vault.yml   # This file would be encrypted with `ansible-vault encrypt`.
  tasks:
    - name: Ensure OpenSCAP is installed
      dnf:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Ensure the file exists (optional)
      stat:
        path: /ssg-fedora-ds.xml
      register: result

    - name: Fail if file does not exist (optional)
      fail:
        msg: "The file is not present on the destination host!"
      when: not result.stat.exists

    # If you have some module to use the file, include it here. 
    # Otherwise, the below task is just a placeholder.
    # - name: Use the file
    #   your_module_here:
    #     file_path: /ssg-fedora-ds.xml

    - name: Run OpenSCAP scan
      command:
        cmd: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --results /scan-results.xml /ssg-fedora-ds.xml
      register: scan_results

    - name: Display the scan results
      debug:
        var: scan_results.stdout_lines

