---
- hosts: all
  become: yes
  vars_files:
    - /etc/ansible/playbooks/vars/vault.yml   # This file would be encrypted with `ansible-vault encrypt`.
  tasks:
    - name: Ensure OpenSCAP is installed
      dnf:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Copy the Fedora SCAP profile to target
      copy:
        src: /etc/ansible/playbooks/ssg-fedora-ds.xml
        dest: /tmp/ssg-fedora-ds.xml
        mode: '0644'

    - name: Run OpenSCAP scan
      command:
        cmd: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --results /tmp/scan-results.xml /tmp/ssg-fedora-ds.xml

